
spring:
  config:
    activate:
      on-profile: test
    import: optional:configserver:http://localhost:9296
    
  cloud:
    config:
      discovery:
        enabled: false
eureka:
  client:
    enabled: false
  
ribbon:
  eureka:
    enabled: false