spring:
  profiles:
    default: dev
  # cloud:
  #   config:
  #     uri: "http://localhost:8088"
  #     enabled: true
  #     fail-fast: true
  # config:
  #   import: "optional:configserver:http://localhost:8088"
  
   



