

spring:
  devtools: 
    restart:
      enabled: true
    livereload: 
      enabled: true
  config:
    activate:
      on-profile: dev
  
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9191


  neo4j:
    uri: neo4j://localhost:7687/recommendations
    authentication:  
      username: neo4j
      password: password

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://localhost:7000/eureka/