


neo4j.host: neo4j 

spring:
  devtools: 
    restart:
      enabled: true
    livereload: 
      enabled: true
  config:
    activate:
      on-profile: docker
  kafka:
    
    retry:
      topic:
        enabled: true
        attempts: 10
    
    consumer:
      auto-offset-reset: earliest
      
      group-id: recommendation-events-listener-group
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: kafka_broker:9191
  neo4j:
    uri: bolt://neo4j-db:7687/recommendations
    authentication:  
      username: username
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
