

spring:
  config:
    activate:
      on-profile: production
  
  kafka:
    consumer:
      group-id: test
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: kafka_broker:9191


  neo4j:
    uri: neo4j://localhost:7687/recommendations
    authentication:  
      username: neo4j
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
