pipeline {
   agent any

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }

        stage('Run Provider Verify Test') {
            steps {
                sh 'mvn clean -Dtest=userProducerKafka test -pl date-provider'
            }
        }
        stage('Run Provider Verify Test') {
            steps {
                sh 'mvn clean -Dtest=friendProducerKafka test -pl date-provider'
            }
        }
    }
}