spring:
  application:
    name: config-service
  profiles: 
    default: dev
  cloud:
    config:
      server:
        git:
          # basedir: config
          clone-on-start: true
          try-master-branch: true
          force-pull: true
          username: philipdaquin
          password: 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
          uri: https://github.com/philipdaquin/friend-recommendation-infra.git
          search-paths:
          - config/api_gateway
          - config/user_service
          - config/friend_service
          - config/recommendation_service
          - config/discovery_service
          
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8088


---
spring:
  config: 
    activate:
      on-profile: docker
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

---

spring:
  config: 
    activate:
      on-profile: kubernetes
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
