spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # basedir: config
          clone-on-start: true
          try-master-branch: true
          username: philipdaquin
          password: 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
          uri: https://github.com/philipdaquin/friend-recommendation-infra.git
          search-paths:
          - config/api_gateway
          - config/user_service
          - config/friend_service
          - config/recommendation_service
          - config/discovery_service
          
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8088


