version: "1.0"

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports: 
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      redis-db:
        condition: service_started
    networks:
      - gateway-service-local


  redis-db:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - gateway-service-local

networks:
  gateway-service-local:
    external: false