
spring:
  profiles:
    active: development
  application:
    name: discovery-service
  # config:
  #   import: optional:configserver:${CONFIG_SERVER_URL}:http://localhost:9296

server:
  port: 8761
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR

---
spring:
  config:
    activate:
      on-profile: development
eureka:
  instance:
    prefer-ip-address: true

--- 
spring:
  config:
    activate:
      on-profile: docker 
eureka:
  instance:
    prefer-ip-address: true
---

spring:
  config:
    activate:
      on-profile: test