
spring:
  application:
    name: discovery-service
  profiles: 
    default: dev
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8761

management: 
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://tempo:9411/api/v2/spans"
  otlp:
    metrics:
      export:
        url: "http://otel-collector:4318/v1/metrics"
        step: 10s
        resource-attributes:
          service:
            name: ${spring.application.name}  
    tracing:
      endpoint: "http://otel-collector:4318/v1/traces"

  prometheus:
    metrics:
      export:
        step: 10s
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR

---
spring:
  config:
    activate:
      on-profile: development
eureka:
  instance:
    prefer-ip-address: true

--- 
spring:
  config:
    activate:
      on-profile: docker 
eureka:
  instance:
    prefer-ip-address: true
---
spring:
  config:
    activate:
      on-profile: kubernetes 
eureka:
  instance:
    prefer-ip-address: true
---

