version: '1.0'

services:
  recommendation-service:
    build: .
    container_name: recommendation-service
    ports: 
      - "7002:7002" 
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      neo4j:
        condition: service_started
    networks:
      - recommendation-service-local 

    # Neo4j
  neo4j:
    container_name: neo4j
    image: bitnami/neo4j:latest
    ports:
      - "7475:7474"
      - "7687:7687"
      - "7473:7473"
    networks:
      - recommendation-service-local 
    environment:
      - NEO4J_PASSWORD= password
      - NEO4J_HOST= username
      - NEO4J_ALLOW_UPGRADE=true
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

  



networks:
  recommendation-service-local:
    external: false 