####
#   
#   Development 
#
####




# management:
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans
#   otlp:
#     metrics:
#       export:
#         url: http://localhost:4318/v1/metrics
#         step: 10s
#         resource-attributes:
#           service:
#             name: ${spring.application.name}  
#     tracing:
#       endpoint: "http://localhost:4318/v1/traces"



postgres.port: 5432
postgres.host: "postgres_container_test"
postgres.database-name: users 
postgres.username: postgres
# postgres.url: postgresql://${postgres.:localhost}:${postgres.port}/${postgres.database-name}
postgres.url: postgresql://${DB_HOST:localhost}:${postgres.port}/${postgres.database-name}
PRODUCER_TOPIC: user


redis.host: localhost
redis.port: 6379

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  config:
    activate:
      on-profile: dev 
  datasource:
    url: ${postgres.url}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  r2dbc:
    
    url: r2dbc:${postgres.url}
    # url: r2dbc:postgresql://localhost:5432/users
    username: postgres
    password: password
  liquibase:
    url: jdbc:${postgres.url}
    user: postgres
    password: password

  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
  
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true

    service-registry:
      auto-registration:
        enabled: true
        fail-fast: true

  ##
  #  Apache Kafka Produder 
  ##
  kafka:
    bootstrap-servers: localhost:9191
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant-path-matcher
######
#  Service Registry 
#####
eureka:

  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://localhost:7000/eureka/


