spring:
  application:
    name: user-service
  profiles:
    default: dev

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7000

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

---

# ####
# #   
# #   Development 
# #
# ####
# postgres.port: 5432
# postgres.host: localhost
# postgres.database-name: users 
# postgres.url: postgresql://${postgres.host:localhost}:${postgres.port}/${postgres.database-name}
# PRODUCER_TOPIC: user

# spring:
#   main.allow-bean-definition-overriding: true
#   devtools:
#     restart:
#       enabled: true
#     livereload:
#       enabled: true
#   config:
#     activate:
#       on-profile: development 
#   datasource:
#     url: ${postgres.url}
#     username: postgres
#     password: 123
#     driver-class-name: org.postgresql.Driver
#   r2dbc:
#     # url: r2dbc:${postgres.url}
#     url: r2dbc:postgresql://localhost:5432/users
#     username: postgres
#     password: 123
#   ##
#   #  Apache Kafka Produder 
#   ##
#   kafka:
#     bootstrap-servers: localhost:9091
#     producer:
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
#   # mvc:
#   #   pathmatch:
#   #     matching-strategy: ant-path-matcher
# ######
# #  Service Registry 
# #####
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://discovery-service:8761/eureka/

# --- 


# ####
# #   
# #   Production 
# #
# ####
# postgres.port: 5432
# postgres.host: user_db
# postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/
# postgres.database-name: postgres 
# PRODUCER_TOPIC: user

# spring:
#   devtools:
#     restart:
#       enabled: false
#     livereload:
#       enabled: true
#   config:
#     activate:
#       on-profile: production 
#   datasource:
#     url: ${postgres.url}
#     username: username
#     password: password
#     driver-class-name: org.postgresql.Driver
#   r2dbc:
#     url: r2dbc:${postgres.url}
#   ##
#   #  Apache Kafka Produder 
#   ##
#   kafka:
#     bootstrap-servers: localhost:9091
#     producer:
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
#   # mvc:
#   #   pathmatch:
#   #     matching-strategy: ant-path-matcher
# ######
# #  Service Registry 
# #####
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://discovery-service:8761/eureka/
