spring:
  application:
    name: user-service
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7000

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

---
####
#   
#   Production 
#
####
postgres.port: 5432
postgres.host: localhost
postgres.database-name: user 
# postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/
# postgres.url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port}/

postgres.url: postgresql://${postgres.host}:${postgres.port}/${postgres.database-name}
PRODUCER_TOPIC: user

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  config:
    activate:
      on-profile: prod 
  datasource:
    url: ${postgres.url}
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:${postgres.url}
    username: username
    password: password
  liquibase:
    url: ${postgres.url}
    user: ${postgres.username}
    password: ${postgres.password}
  ##
  #  Apache Kafka Produder 
  ##
  kafka:
    bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant-path-matcher
######
#  Service Registry 
#####
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
