####
#   
#   Development 
#
####
postgres.port: 5432
postgres.host: "postgres_container_test"
postgres.database-name: users 
postgres.username: postgres
# postgres.url: postgresql://${postgres.:localhost}:${postgres.port}/${postgres.database-name}
postgres.url: postgresql://${DB_HOST:localhost}:${postgres.port}/${postgres.database-name}
PRODUCER_TOPIC: user


redis.host: "localhost"
redis.port: 6379

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  config:
    activate:
      on-profile: dev 
  datasource:
    url: ${postgres.url}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  r2dbc:
    
    url: r2dbc:${postgres.url}
    # url: r2dbc:postgresql://localhost:5432/users
    username: postgres
    password: password
  liquibase:
    url: jdbc:${postgres.url}
    user: postgres
    password: password

  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
  

  ##
  #  Apache Kafka Produder 
  ##
  kafka:
    bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant-path-matcher
######
#  Service Registry 
#####
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


