
postgres.port: 5432
postgres.host: localhost
postgres.url: ${spring.datasource.url}
postgres.database-name: postgres
prometheus.enabled: false


redis.host: "localhost"
redis.port: 6379

spring:
  config:
    activate:
      on-profile: test
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  liquibase:
    url: ${spring.datasource.url}
    user: postgres
    password: password
  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      

eureka:
  client:
    enabled: false
