spring:
  application:
    name: user-service

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7000

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN

---

####
#   
#   Development 
#
####
postgres.port: 5432
postgres.host: "127.0.0.1"
postgres.database-name: users 
postgres.username: postgres
# postgres.url: postgresql://${postgres.:localhost}:${postgres.port}/${postgres.database-name}
postgres.url: postgresql://${postgres.host}:${postgres.port}/${postgres.database-name}
PRODUCER_TOPIC: user

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  config:
    activate:
      on-profile: dev 
  datasource:
    url: ${postgres.url}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  r2dbc:
    
    url: r2dbc:${postgres.url}
    # url: r2dbc:postgresql://localhost:5432/users
    username: postgres
    password: password
  liquibase:
    url: jdbc:${postgres.url}
    user: postgres
    password: password
  ##
  #  Apache Kafka Produder 
  ##
  kafka:
    bootstrap-servers: localhost:9091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant-path-matcher
######
#  Service Registry 
#####
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


