spring:
  application:
    name: user-service
  profiles:
    default: dev

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7000

management: 
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  # zipkin:
  #   tracing:
  #     endpoint: "http://localhost:9411/api/v2/spans"
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
        step: 10s
        resource-attributes:
          service:
            name: ${spring.application.name}  
    tracing:
      endpoint: "http://localhost:4318/v1/traces"

  prometheus:
    metrics:
      export:
        step: 10s
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  # level:
  #   root: INFO
  #   kafka.*: WARN
  #   org.springframework.*: INFO
  #   org.apache.kafka.*: WARN


