spring:
  application:
    name: user-service
  profiles:
    default: dev

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7000

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN