# version: '3.8'
# services:

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     restart: always
#     ports:
#       - '9090:9090'
#     volumes:
#       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#       - '--web.external-url=http://localhost:9090'

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     restart: always
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./monitoring/grafana/data:/var/lib/grafana
#       - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
#     environment:
#       GF_SECURITY_ADMIN_USER: admin
#       GF_SECURITY_ADMIN_PASSWORD: admin

#   alertmanager:
#     image: prom/alertmanager:latest
#     container_name: alertmanager
#     ports:
#       - '9093:9093'
#     volumes:
#       - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
#     command:
#       - '--config.file=/etc/alertmanager/alertmanager.yml'
#       # - '--web.external-url=http://localhost:9093'

#   cadvisor:
#     image: gcr.io/cadvisor/cadvisor:latest
#     container_name: cadvisor
#     restart: always
#     ports:
#       - '8080:8080'
#     volumes:
#       - /:/rootfs:ro
#       - /var/run:/var/run:rw
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
#     depends_on:
#       redis:
#         condition: service_started

  
#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#     - 6380:6380
#   # loki:
#   #   image: grafana/loki:2.7.3
#   #   container_name: loki
#   #   command: -config.file=/etc/loki/local-config.yaml
#   #   ports:
#   #     - "3100:3100"

#   # tempo:
#   #   image: grafana/tempo:2.0.0
#   #   container_name: tempo
#   #   command: -config.file /etc/tempo-config.yml
#   #   ports:
#   #     - "3110:3100"     # Tempo
#   #     - "4317:4317"     # OTLP
#   #     - "9411:9411"     # Zipkin
#   #   volumes:
#   #     - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
  