pipeline { 
    agent any 

    environment { 
        dockerImageName = "philipasd/friend_service"
    }
    stages { 

        stage('Checkout') { 
            steps { 
                checkout scm 

            }
        }

        stage('Compile Code') {
            steps {
                sh 'cd friend_service && ./mvnw clean compile'
            }
        } 
        stage('Unit Test') {
            steps {
                sh 'cd friend_service && ./mvnw test'
            }
        } 
        stage('Integration Test') { 
            steps { 
                sh 'cd friend_service && ./mvnw verify'
            }
        } 
        stage('Package Artifact Jar') {
            steps { 
                sh 'cd friend_service && ./mvnw package'
            }
        } 
        stage('Build Docker Image') {
            environment {
                // COMMIT_ID = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                // COMMIT_ID = env.BUILD_NUMBER
            }
            steps {
                sh "docker build -t friend-service -f friend-service/Dockerfile friend-service/"
            }
            // steps {
            //     sh "docker build -t ${dockerImageName} -f friend_service/Dockerfile friend_service/"
            // }
        } 
        stage('Push Image to DockerHub') {
            steps { 
                script { 
                    // docker.withDockerRegistry('https://registry.hub.docker.com', registryCredential) { 
                    //     dockerImage.push()
                    //     dockerImage.push('latest')
                    // }
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${env.BUILD_NUMBER}")
                    }
                }
            }
        } 
        stage('Update Kubertenes Deployment Instance') {
            steps { 
                sh 'kubectl apply -f deployments/' 
            }
        } 

        /*

            Update the Manifest File for UserService

        */
        stage('Trigger ManifestUpdate') {
                echo "triggering updatemanifestjob"
                build job: 'updateFriendServiceManifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
        }
    }
    post { 
        success { 
            echo "Build Success"
            echo "Successfully built ${env.JOB_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}" 
        }
        failure { 
            echo "Build failed - ${env.JOB_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}"
        }
        aborted { 
            echo "${env.JOB_NAME} Build - ${env.BUILD_ID} Aborted!"
        }
    }
}

