apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_gateway
spec:
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
      labels:
        app: api_gateway
    spec:
      containers:
      - name: api-gateway
        image: philipasd/api_gateway
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090

--- 
apiVersion: v1
kind: Service
metadata:
  name: api_gateway_svc
spec:
  type: LoadBalancer
  selector:
    app: api_gateway
  ports:
  - port: 80
    targetPort: 9090
