apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend_deployment
spec:
  selector:
    matchLabels:
      app: friend_deployment
  template:
    metadata:
      labels:
        app: friend_deployment
    spec:
      containers:
      - name: friend_deployment
        image: philipasd/friend_service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7002


---

apiVersion: v1
kind: Service
metadata:
  name: friend_service
spec:
  selector:
    app: friend_deployment
  ports:
  - port: 80
    targetPort: 7002
