apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation_deployment
spec:
  selector:
    matchLabels:
      app: recommendation_deployment
  template:
    metadata:
      labels:
        app: recommendation_deployment
    spec:
      containers:
      - name: recommendation_deployment
        image: philipasd/philipasd/recommendation_service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7001


--- 

apiVersion: v1
kind: Service
metadata:
  name: recommendation_service
spec:
  selector:
    app: recommendation_deployment
  ports:
  - port: 80
    targetPort: 7001
