version: "1.0"

services:
  user-service:
    build: .
    container_name: user-service
    ports: 
      - "7000:7000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/users
    depends_on:
      postgres-db:
        condition: service_started
    networks:
      - user-service-local

  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-container-test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./document/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    networks:
      - user-service-local 
  
networks:
  user-service-local:
    external: false
volumes:
  db-data: