version: "1.0"

services:

  user_api:
    # image: user_service
    build: .
    ports: 
      - "7000:7000"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=postgresql://postgreSql:5432/users
    depends_on:
      postgreSql:
        condition: service_started
    networks:
      - user-service-local

  postgreSql:
    image: postgres
    container_name: postgres_container_test
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - PGDATA= /data/postgres
      - POSTGRES_DB=users
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db", "-U", "postgres", "-h", "database"]
      interval: 10s
      timeout: 5s
      retries: 3 
    networks:
      - user-service-local 
  
  
networks:
  user-service-local:
    external: false
