pipeline { 
    agent any 
    environment { 
        APP_IMAGE = "philipasd/user_service"
        dockerImage = ""
    }
    stages { 

        stage('Checkout') { 
            steps { 
                checkout scm 
            }
        }

        stage('Compile Code') {
            steps {
                sh 'cd user_service && ./mvnw clean compile'
            }
        } 

        
        
        // stage('Static Code Analysis') {
        //     // environment {
        //     //     SONAR_URL = "http://34.201.116.83:9000"
        //     // }
        //     // steps {
        //     //     withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
        //     //         sh 'cd user_service && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        //     //     }
        //     // }
        //     steps { 
        //         sh 'echo sonar analysis'
        //     }
        // }
        
        
        // stage('Unit Test') {
        //     steps {
        //         sh 'cd user_service && ./mvnw test'
        //     }
        // } 
        
        
        // stage('Integration Test') { 
        //     steps { 
        //         // sh 'cd user_service && ./mvnw clean test -Pintegration-testing'
        //         // echo 'integration testing'
        //          sh 'cd user_service && ./mvnw test'
        //     }
        // } 

        // stage('End to End Test') { 
        //     steps { 
        //         // sh 'cd user_service && ./mvnw clean test -Pintegration-testing'
        //         // echo 'e2e tests'
        //          sh 'cd user_service && ./mvnw test'

        //     }
        // } 
      
        // stage('Acceptance Test') { 
        //     steps { 
        //         // sh 'cd user_service && ./mvnw clean test -Pintegration-testing'
        //         // echo 'acceptance tests'
        //          sh 'cd user_service && ./mvnw test'

        //     }
        // } 

        // stage("Performance tests") { 
        //     steps { 
        //         // sh 'cd user_service && ./mvnw clean jmeter:jmeter'
        //         // echo 'performance test'
        //         sh 'cd user_service && ./mvnw test'
        //     }
        // }
        stage('Package Artifact Jar') {
            steps { 
                sh 'cd user_service && ./mvnw package'
            }
        } 

        stage('Build Docker Image') {
            steps { 
                sh "docker build -t ${APP_IMAGE} -f user_service/Dockerfile user_service/"
            }
        } 
        stage('Push Image to DockerHub') {
            steps { 
                script { 
                        docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
                        dockerImage.push("${env.BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
                // withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'docker_pass', usernameVariable: 'docker_user')]) {
                //     sh 'docker login -u ${docker_user} -p ${docker_pass}'
                //     sh 'docker push ${APP_IMAGE}:${env.BUILD_NUMBER}'
                // }
            }
        } 

        // // 
        // // UNTESTED MANIFEST FILE LISTENER
        // // 
        // stage('Trigger Manifest Update') {
        //         echo "triggering updatemanifestjob"
        //         build job: 'updateFriendServiceManifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
        // }
    }
    post { 
        success { 
            echo "Build Success"
            echo "Successfully built ${env.JOB_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}" 
        }
        failure { 
            echo "Build failed - ${env.JOB_NAME} - ${env.BUILD_ID} on ${env.BUILD_URL}"
        }
        aborted { 
            echo "${env.JOB_NAME} Build - ${env.BUILD_ID} Aborted!"
        }
    }
}