global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:7000"]

    # 
    # container Advisor
    # - Analyses and exposes resource usage and performance data from 
    # running containers. 
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ["alertmanager:9093"]
  