global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'otel-collector'
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: 'user-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ["user-service:7000"]


    # 
    # container Advisor
    # - Analyses and exposes resource usage and performance data from 
    # running containers. 
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
  