spring:
  config:
    activate:
      on-profile: dev 

  data:
    mongodb:
      database: mongo
      host: localhost
      port: 27017
      

  kafka:
    template:
      default-topic: friend
    bootstrap-servers: localhost:9191
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://localhost:7000/eureka/

PRODUCER_TOPIC: friend
