spring:
  application:
    name: friend-service
  profiles: 
    default: dev
  config: 
    import: "optional:configserver:http://localhost:8088"

---

spring:
  config: 
    activate:
      on-profile: test
    import: "optional:configserver:http://localhost:8088"

---

spring:
  config: 
    activate:
      on-profile: prod
    import: "optional:configserver:http://config-service:8088"

---
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      fail-fast: true
      retry:
        max-attempts: 60
  config: 
    activate:
      on-profile: docker 
    import: "optional:configserver:http://config-service:8088"

---

spring:
  config: 
    activate:
      on-profile: kubernetes 
    import: "optional:configserver:http://config-service:8088"
