spring:
  config:
    activate:
      on-profile: prod 

  data:
    mongodb:
      database: mongo
      host: mongo-db
      port: 27017
      password: password
      username: username
  kafka:
    template:
      default-topic: friend
    bootstrap-servers: kafka_broker:9191
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

PRODUCER_TOPIC: friend

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/