spring:
  application:
    name: friend-service
  profiles:
    default: dev

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 7001

logging:
  level:
    org.springframework.transaction: TRACE
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.apache.kafka.*: WARN